services:
  - type: web
    name: quilt-hub-test1
    runtime: python
    rootDir: quilt_hub
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
